### PR TITLE
Add ability to move caret by arrow keys

### PR DESCRIPTION
**Pull request by AlysCole**
This commit will separate the function 'updateCaret' into two:
'updateCaretAtInput' (handles the movement of the caret when data is
entered/deleted) and 'updateCaretAtSpecialKey' (handles the movement
of the caret when a key is pressed).

The added function 'updateCaretAtSpecialKey' will handle the movement
of the caret by the arrow keys (left, up, right, and down).

Close issue #52.

### CODE REVIEW

**Comment by Matthew-Burfield** [comment]
@AlysCole I'm thinking maybe we should move out the arrow keys from the special keys list, since that special keys list contains a lot of keys that aren't movement keys, like all the function keys, esc and cap lock keys etc.

Also, do you think we can find a way to have all the caret updates from one function? I think I understand why you split it up, the caret updates depend on the document being updated first, and the caret movement updates need to happen without the document updating so it gets tricky - something tells me it should all be in one function though so all caret updates are done in one place.

What do you think?

**Review by Matthew-Burfield — COMMENTED** [review]
.

**Comment by AlysCole** [comment]
@Matthew-Burfield Since the special keys list should take care of any special keys potentially using the 'default' switch case of the updateCaret function, I think that's a fair point! The commit 12e83b8 introduces the functions combined!

**Review by Matthew-Burfield — APPROVED** [review]
Nice one @AlysCole! Lets merge this in now, and then come back and write some tests for it after you have the cursor blinker displaying

**Pull request merged**
